# Generated by Django 2.1.2 on 2019-06-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category_Article', to='article.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='info',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='info',
            name='note',
            field=models.TextField(verbose_name='お知らせ'),
        ),
        migrations.AlterField(
            model_name='info',
            name='public_date',
            field=models.DateField(blank=True, null=True, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_category', to='article.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='サイト概要'),
        ),
        migrations.AlterField(
            model_name='site',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='site',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='開設日'),
        ),
    ]
