# Generated by Django 2.1.2 on 2019-06-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190624_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='block_fix',
            field=models.TextField(blank=True, null=True, verbose_name='指摘'),
        ),
    ]
