# Generated by Django 2.1.2 on 2019-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190620_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='画像名'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='画像説明'),
        ),
        migrations.AlterField(
            model_name='image',
            name='origin',
            field=models.ImageField(upload_to='uploads/%y/%m/%d/', verbose_name='ファイル選択'),
        ),
    ]
