# Generated by Django 2.1.2 on 2019-06-24 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_articledetail_block_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_fix', models.TextField(blank=True, null=True, verbose_name='指摘')),
                ('confirm_date', models.DateField(blank=True, verbose_name='確認日')),
                ('close_date', models.DateField(blank=True, verbose_name='対応日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleDetail')),
                ('created_by', models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fix_CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
