# Generated by Django 2.1.2 on 2019-06-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefix',
            options={'verbose_name': '指摘', 'verbose_name_plural': '指摘'},
        ),
        migrations.RenameField(
            model_name='articlefix',
            old_name='article',
            new_name='articledetail',
        ),
    ]
