# Generated by Django 2.1.2 on 2019-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190624_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefix',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='確認日'),
        ),
    ]
